function res = branch12Project_backprop(input, net, res)
[sz1,sz2,sz3,sz4] = size(input);
for j = 1:sz4/12
    for i =1:12
        index = i+(j-1)*12;
        x(:,:,:,1) = input(:,:,:,index);
        l = net.layers{i+17} ;
        [dzdx, res(i+17).dzdw{1}, res(i+17).dzdw{2}] = ...
                vl_nnconv(x, l.weights{1}, l.weights{2}, ...
                          res(30).dzdx(:,:,:,j), ...
                          'pad', l.pad, 'stride', l.stride, ...
                          'CuDNN') ;
%         out(:,:,:,i) = vl_nnconv(x, l.weights{1}, l.weights{2}, ...
%                        'pad', l.pad, 'stride', l.stride, ...
%                        'CuDNN') ;
%         res(18).dzdx = [];
        res(18).dzdx(:,:,:,index) = single(gather(dzdx));
    end
%     tmp = mean(out,4);
%     res(30).x(:,:,:,j) = tmp;    
end
res(18).dzdx = gpuArray(single(res(18).dzdx));
flag =1;
% 
%             [res(i).dzdx, res(i).dzdw{1}, res(i).dzdw{2}] = ...
%                 vl_nnconv(res(i).x, l.weights{1}, l.weights{2}, ...
%                           res(i+1).dzdx, ...
%                           'pad', l.pad, 'stride', l.stride, ...
%                           cudnn{:}) ;