projectorSize = 2048;
load('./data/12projectors_2048.mat')
for i = 12:-1:1
  layers{17+i} = struct('type', 'conv', 'name', sprintf('%s%d', 'fc_b', i), ...
                           'weights', {{0.01 * randn(1, 1, 4096, projectorSize, 'single'), ...
                           0.1*ones(1,projectorSize,'single')}}, ...
                           'stride', 1, ...
                           'pad', 0, ...
                           'learningRate', [1 2], ...
                           'weightDecay', [1 0]) ;
   tmp = CORE_TENSOR_pose{i}';
   nM = 10*sqrt(sum(tmp.^2,2));
   ntmp = bsxfun(@rdivide, tmp , nM);
   layers{17+i}.weights{1}(1,1,:,:) = ntmp;
end